version: "3.5"

services:
  control-app:
    build: ./control_app
    container_name: control_docs_app
    expose:
      - 8001
    ports:
      - "8001:8001"
    volumes:
      - control_volume:/home/app/control_app

  manage-app:
    build: ./manage_app
    container_name: manage_docs_app
    expose:
      - 8002
    ports:
      - "8002:8002"
    volumes:
      - manage_volume:/home/app/manage_app

volumes:
  control_volume:
  manage_volume:
